WebApplication3/Controllers/NewsController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class NewsController : Controller
    {
        private readonly SiteContext _siteContext;
        private readonly UserManager<User> _userManager;

        public NewsController(SiteContext sitecontext, UserManager<User> userManager)
        {
            _siteContext = sitecontext;
            _userManager = userManager;
        }
        public IActionResult Details(int id)
        {
            var newsItem = _siteContext.News.FirstOrDefault(n => n.Id == id);
            var comments = _siteContext.Comments.Where(x => x.NewsId == id).OrderByDescending(x => x.Date).ToList();
            newsItem.Comments = comments;
            return View(newsItem);
        }

        public IActionResult AddComment(int newsId, string text)
        {
            if (!text.IsNullOrEmpty())
            {
                var news = _siteContext.News.FirstOrDefault(n => n.Id == newsId);
                Comment comment = new Comment();
                comment.NewsId = newsId;
                comment.Text = text;
                comment.Date = DateTime.Now;
                comment.SenderId = _userManager.GetUserId(User);
                comment.SenderName = User.Identity.Name;
                news.Comments.Add(comment);
                _siteContext.SaveChanges();
            }
            return RedirectToAction("Details", new {id = newsId});
        }

        public IActionResult Delete(int id, int newsId)
        {
            var comment = _siteContext.Comments.FirstOrDefault(x => x.Id == id);
            _siteContext.Comments.Remove(comment);
            _siteContext.SaveChanges();
            return RedirectToAction("Details", new {id = newsId});
        }
    }
}

WebApplication3/Controllers/SearchController.cs
using Microsoft.AspNetCore.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class SearchController : Controller
    {
        private readonly SiteContext _siteContext;
        public SearchController(SiteContext siteContext)
        {
            _siteContext = siteContext;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Find(string title)
        {
            var found = _siteContext.News.Where(x => x.Title.Contains(title)).OrderByDescending(x => x.Date).ToList();
            return View(found);
        }
    }
}

WebApplication3/Views/Search/Find.cshtml
@using System.Text.Json;
@using Microsoft.AspNetCore.Identity;
@using WebApplication3.Models;
@model List<News>
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a style="font-size:30px" class="nav-link text-dark text" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" method="get" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" method="get" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" method="get" asp-controller="Account" asp-action="Login">Log in</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <p class="nav-link text-dark text">Hi, @User.Identity?.Name!</p>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input class="nav-link text-dark btn" style="box-shadow:none" type="submit" value="Exit the account" />
                                </form>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <form method="post" asp-controller="Admin" asp-action="Index">
                                        <input class="nav-link text-dark btn" style="box-shadow:none" type="submit" value="Admin" />
                                    </form>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <form asp-action="Find" method="post">
        <div class="form-group">
            <label for="title">Enter title:</label>
            <input name="title" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
    <div class="row">
        @foreach (var newsItem in Model)
        {
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <img src="@newsItem.ImageUrl" alt="@newsItem.Title" class="card-img-left">
                        <div class="text-right">
                            <h5 class="card-title">@newsItem.Title</h5>
                            <p class="card-text"><small class="text-muted">@newsItem.Date.ToShortDateString()</small></p>
                            <a href="@Url.Action("Details", "News", new { slug = newsItem.Title, id = newsItem.Id })" class="btn btn-primary">Дізнатися більше...</a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</body>
</html>

WebApplication3/Views/Search/Index.cshtml
@using System.Text.Json;
@using Microsoft.AspNetCore.Identity;
@using WebApplication3.Models;
@inject SignInManager<User> SignInManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog</title>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a style="font-size:30px" class="nav-link text-dark text" asp-area="" asp-controller="Home" asp-action="Index">Blog</a>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" method="get" asp-controller="Search" asp-action="Index">Search</a>
                        </li>
                        @if (!SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" method="get" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" method="get" asp-controller="Account" asp-action="Login">Log in</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <p class="nav-link text-dark text">Hi, @User.Identity?.Name!</p>
                            </li>
                            <li class="nav-item">
                                <form method="post" asp-controller="Account" asp-action="Logout">
                                    <input class="nav-link text-dark btn" style="box-shadow:none" type="submit" value="Exit the account" />
                                </form>
                            </li>
                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item">
                                    <form method="post" asp-controller="Admin" asp-action="Index">
                                        <input class="nav-link text-dark btn" style="box-shadow:none" type="submit" value="Admin" />
                                    </form>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <form asp-action="Find" method="post">
        <div class="form-group">
            <label for="title">Enter title:</label>
            <input name="title" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary">Search</button>
    </form>
</body>
</html>